### ISSUE TITLE
Fenced code blocks aren't highlighted in markdown

### ISSUE THREAD

**Issue by contextnerror** [wangweixuan/yithemes#10]
![Screen Shot 2022-09-23 at 3 58 45 PM](https://user-images.githubusercontent.com/54487525/192067331-7264bea9-d58d-4ac8-9f2b-717276cd0056.png)
Yi Dark is on the left, Atom is on the right.

**Comment by wangweixuan** [comment]
Thanks for reporting! A new version has been published to fix this problem!
