### ISSUE TITLE
Add a shadow to the bottom side of the sticky widget

### ISSUE THREAD

**Issue by ptsl** [wangweixuan/yithemes#12]
**Problem Description**
1. Go to the VSCode menu. Enable **View -> Sticky Scroll**.

This enabled the sticky scroll widget. This widget always shows the current class and method.

2. Go to Settings (`Ctrl+,`).
3. Go to **Editor > Sticky Scroll: Default Model**.
4. Try all settings. The last setting (`indentationModel`) will make the sticky window as tall as possible.

Now, there is no line showing the border between the sticky widget and the rest of the editor. There is nothing to show that some lines of the function definition are missing, save for the gap in line numbers. (Line 57 is followed by Line 60 and then by Line 76.)

![image](https://github.com/wangweixuan/yithemes/assets/5755386/02aa9ce8-534b-4f1a-8679-92bee79f0f8e)

Please, add a shadow to the bottom side of the sticky widget (`<div class="sticky-widget">`). Or maybe just a single line. Or use a different background for the sticky widget, just to give a few ideas.

In general, it should look similar to this (using the Dark High Contrast theme):

![image](https://github.com/wangweixuan/yithemes/assets/5755386/ff7e9e60-0cef-4653-82d7-786d038eb467)

**Comment by wangweixuan** [comment]
I have changed background and shadow colors in the new version.

<img width="382" alt="screenshot" src="https://github.com/wangweixuan/yithemes/assets/24620923/b72e86cf-5381-406a-a494-7db637cde9b2">

**Comment by ptsl** [comment]
I've just updated the plugins and it seems great! Thank you for your work!
