### ISSUE TITLE
No CSS syntax highlighting when using style attribute in HTML

### ISSUE THREAD

**Issue by jrevolve** [wangweixuan/yithemes#13]
This is my favorite Atom One Dark port.

There are a few problems when the `style` attribute is used in HTML. As you can see, there's no CSS syntax highlighting. Furthermore, the opening and closing quotation marks have different colors.

<img width="742" alt="image" src="https://github.com/wangweixuan/yithemes/assets/139791737/cff7b99f-ed5c-488f-92fe-6019a01c4353">

**Comment by wangweixuan** [comment]
Thanks for reporting. I have uploaded a new version that fixes the closing quotation marks.

Seems inline CSS highlighting is not supported by VS Code yet (https://github.com/textmate/html.tmbundle/issues/88). You can install the [Inline CSS Color](https://marketplace.visualstudio.com/items?itemName=outofsync42.inline-css-color) extension by outofsync42 as a workaround. (My new version contains support for that extension, so you need not follow its setup steps.)
