### ISSUE TITLE
statusBar.debuggingForeground and statusBar.noFolderForeground illegible on light theme

### ISSUE THREAD

**Issue by chibicode** [wangweixuan/yithemes#2]
Hi again! Currently the text on the status bar is illegible on the light theme if it's debugging or there's no folder:

<img width="431" alt="screen shot 2019-03-01 at 6 54 57 pm" src="https://user-images.githubusercontent.com/992008/53676165-8f8f5c00-3c53-11e9-92ee-3feeeea94990.png">

The problem seems to be these lines:

https://github.com/wangweixuan/yithemes/blob/master/src/workbench.ts#L286-L291

**Comment by wangweixuan** [comment]
Fixed in 8a59fd6f71eb71f3335974ad28c8e93616f0fb26.
Now the status bar doesn't differentiate when there is no folder opened. And the foreground is changed to white when debugging.
