### ISSUE TITLE
No clear separation between two documents in compare modus

### ISSUE THREAD

**Issue by marcelhekking** [wangweixuan/yithemes#5]
In the light version, when in the compare modus there is no visible line between the two versions of a document making it very hard to use the slider:
![image](https://user-images.githubusercontent.com/946241/63442171-f0456780-c432-11e9-9856-b7641410c659.png)

This is an example of another light theme where there is a clear line making it versy easy to place the slider:
![image](https://user-images.githubusercontent.com/946241/63442310-2b479b00-c433-11e9-9315-f4e55c441857.png)

**Comment by wangweixuan** [comment]
Thanks for your feedback! I am fixing it.

**Comment by marcelhekking** [comment]
Great !!!

Thank you very much! I already working with it. I have still a very small
issue. I will post it on Github in a GIF.

Regards,
Marcel Hekking
