### ISSUE TITLE
Dragging a tab to relocate can barely be seen

### ISSUE THREAD

**Issue by marcelhekking** [wangweixuan/yithemes#6]
Yi light theme:
![dragging tab yi](https://user-images.githubusercontent.com/946241/63535600-20b00300-c512-11e9-8e38-6eebbf7f570d.gif)

Other light theme:
![dragging tab other theme](https://user-images.githubusercontent.com/946241/63535649-40472b80-c512-11e9-9121-c5772484fe0c.gif)

**Comment by wangweixuan** [comment]
I am fixing it. A darker grayish color should be appropriate.

**Comment by marcelhekking** [comment]
Yes! That works. Thanx for fixing it!!

Regards,
Marcel
