### ISSUE TITLE
在黑色边框的电脑上小黑条辨识度太低

### ISSUE THREAD

**Issue by lovelyjuice** [wangweixuan/yithemes#7]
![IMG_20200121_085826](https://user-images.githubusercontent.com/20644461/72766787-65a8a480-3c2c-11ea-9ec1-9dc79b6f63ad.jpg)
我的电脑边框是黑色的，全屏的时候，小黑条的颜色也是黑色的，与电脑边框贴在一起，难以识别边框和小黑条之间的界限，而且侧栏图标在激活时也没有加粗。

建议把小黑条改成和图标上的小蓝点一样的颜色，既不会显得突兀，也不会有多少蓝色边框的电脑。

**Comment by wangweixuan** [comment]
已修复。
