### ISSUE TITLE
Search term hard to read

### ISSUE THREAD

**Issue by marcelhekking** [wangweixuan/yithemes#8]
Because of the used colors, the part of the search term (after CTRL-SHIFT-P) is hard to read:
![image](https://user-images.githubusercontent.com/946241/122868763-b2b20e00-d32b-11eb-9392-ebe56b6f3eb0.png)

**Comment by wangweixuan** [comment]
Thanks for the feedback! The issue is fixed in version 0.16.0. Background of the selected item is now grey, the same as in Atom One Dark.

**Comment by marcelhekking** [comment]
Thanx for the fix!
