### ISSUE TITLE
When debugging, text under the breakpoint is very hard to read

### ISSUE THREAD

**Issue by marcelhekking** [wangweixuan/yithemes#9]
Due to the color of the breakpoint line, the text under it is very hard to read.
![unreadable_debug_line](https://user-images.githubusercontent.com/946241/150312618-338ba565-1e3c-46d4-9147-9745fca53994.png)
![unreadable_debug_line_light](https://user-images.githubusercontent.com/946241/150312619-025fab54-e398-423e-ac6e-f2f6600b922b.png)

This especially true for the dark variant

**Comment by wangweixuan** [comment]
Thanks for pointing out! I have made the line background transparent so it's easier to read.

<img width="419" alt="fixed dark theme screenshot" src="https://user-images.githubusercontent.com/24620923/150556428-727844e9-2e47-49b7-a3d6-fdac4d819d82.png">
<img width="419" alt="fixed light theme screenshot" src="https://user-images.githubusercontent.com/24620923/150556581-aa30b53c-7af3-4cf7-8707-46f713279045.png">

**Comment by marcelhekking** [comment]
Yes! Works great. Thanx for fixing it so quickly.

Regards,
Marcel
